//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bills
    {
        public int Id { get; set; }
        public Nullable<int> CulturalFund { get; set; }
        public Nullable<int> EmergencyFund { get; set; }
        public Nullable<int> Maintenance { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Water { get; set; }
        public Nullable<int> Light { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
