//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ErrorLogs
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public string Method { get; set; }
        public System.DateTime ErrorOn { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
    }
}
