//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Events
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventTime { get; set; }
    }
}
