//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Users
    {
        public T_Users()
        {
            this.T_OTP_Details = new HashSet<T_OTP_Details>();
            this.T_PasswordHistoryLog = new HashSet<T_PasswordHistoryLog>();
            this.T_Bills = new HashSet<T_Bills>();
            this.T_Complaints = new HashSet<T_Complaints>();
            this.T_FamilyMembers = new HashSet<T_FamilyMembers>();
        }
    
        public int UserId { get; set; }
        public string EmailId { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public bool IsOnline { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> RoleId { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<T_OTP_Details> T_OTP_Details { get; set; }
        public virtual ICollection<T_PasswordHistoryLog> T_PasswordHistoryLog { get; set; }
        public virtual T_Roles T_Roles { get; set; }
        public virtual ICollection<T_Bills> T_Bills { get; set; }
        public virtual ICollection<T_Complaints> T_Complaints { get; set; }
        public virtual ICollection<T_FamilyMembers> T_FamilyMembers { get; set; }
    }
}
